services:
  lgtm-grafana:
    image: grafana/otel-lgtm:0.8.6
    ports:
      - "3000:3000" # Grafana UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "9090:9090" # Prometheus
    environment:
      - ENABLE_LOGS_OTELCOL=true